development:
  host: 127.0.0.1
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  user: pguser
  password: pguser
  pool: 5

test:
  host: 127.0.0.1
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  user: pguser
  password: pguser
  pool: 5
