# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed9b6ae4fbe1ad964e513c8dbe9866267a63a1318d4904f7d3895743892f97ed7786dded1dcb882027829aba1b50da7170d5671da42ffc35ace5205a47ea8b3a

test:
  secret_key_base: ee5ec4905382399a4142062d06f40dae1becbcc4a1104ba6c04f70f57ba28b4d08a3497a934dab28a7fb5e85f9fa468490701e3140830fa8be18913b339093a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
